### POST request for creating a new project
POST http://localhost:8000/api/project/create
Content-Type: application/json
Accept: application/json

{
    "title": "first Project",
    "project_start": "2026-09-07",
    "project_end": "2026-09-10",
    "check_period": "p1d"
}

###
